language: node_js
sudo: false

matrix:
  include:
    - node_js: "4"
      addons:
        postgresql: "9.1"
      dist: precise
    - node_js: "6"
      addons:
        postgresql: "9.4"
    - node_js: "8"
      addons:
        postgresql: "9.6"
